# Generated by Django 5.2.15 on 2026-06-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteamaccount',
            name='steam_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
