# Generated by Django 5.2.13 on 2026-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_default_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
