# Generated by Django 5.2.14 on 2026-05-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicFreeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('thumbnail', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('claim_url', models.URLField(blank=True)),
                ('source', models.CharField(default='mock', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('discount_rate', models.PositiveIntegerField(default=0)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_events', to='games.game')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_events', to='prices.store')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='games.game')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='prices.store')),
            ],
            options={
                'ordering': ['recorded_at'],
                'unique_together': {('game', 'store', 'recorded_at')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('url', models.URLField(blank=True)),
                ('historical_low_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('historical_low_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='games.game')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.store')),
            ],
            options={
                'ordering': ['current_price'],
                'unique_together': {('game', 'store')},
            },
        ),
    ]
