# Generated by Django 5.2.15 on 2026-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['store', 'current_price'], name='prices_pric_store_i_26fa44_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['store', 'discount_rate'], name='prices_pric_store_i_25a096_idx'),
        ),
    ]
