# Generated by Django 5.2.14 on 2026-05-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('steam_app_id', models.CharField(blank=True, max_length=40)),
                ('itad_plain', models.CharField(blank=True, max_length=160)),
                ('thumbnail', models.URLField(blank=True)),
                ('hero_image', models.URLField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developers', models.ManyToManyField(blank=True, to='games.developer')),
                ('genres', models.ManyToManyField(blank=True, to='games.genre')),
                ('publishers', models.ManyToManyField(blank=True, to='games.publisher')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='games_game_title_b7a574_idx'), models.Index(fields=['slug'], name='games_game_slug_161310_idx')],
            },
        ),
    ]
