# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="steam_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="steam_review_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["steam_review_score"], name="games_game_steam_r_8037c2_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["steam_review_count"], name="games_game_steam_r_19972a_idx"),
        ),
    ]
