# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_steam_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="steam_reviews_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
