# Generated by Codex on 2026-06-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_steam_reviews_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_type", models.CharField(choices=[("dlc", "DLC"), ("bundle", "Bundle")], max_length=12)),
                ("external_id", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=240)),
                ("thumbnail", models.URLField(blank=True)),
                ("current_price", models.PositiveIntegerField(default=0)),
                ("original_price", models.PositiveIntegerField(default=0)),
                ("discount_rate", models.PositiveSmallIntegerField(default=0)),
                ("currency", models.CharField(default="KRW", max_length=8)),
                ("url", models.URLField(blank=True)),
                ("is_free", models.BooleanField(default=False)),
                ("included_count", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="related_products", to="games.game"),
                ),
            ],
            options={
                "ordering": ["product_type", "current_price", "title"],
                "unique_together": {("game", "product_type", "external_id")},
                "indexes": [
                    models.Index(fields=["game", "product_type"], name="games_relat_game_id_348ed1_idx"),
                    models.Index(fields=["product_type", "discount_rate"], name="games_relat_product_17a0bc_idx"),
                ],
            },
        ),
    ]
