# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_relatedproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="related_products_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
