# Generated by Django 5.2.13 on 2026-06-25 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_playersnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='games.gamecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gamecomment',
            index=models.Index(fields=['game', '-created_at'], name='games_comment_game_time_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecomment',
            index=models.Index(fields=['user', '-created_at'], name='games_comment_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecommentreaction',
            index=models.Index(fields=['comment', 'value'], name='games_react_comment_val_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecommentreaction',
            index=models.Index(fields=['user', 'value'], name='games_react_user_val_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamecommentreaction',
            unique_together={('comment', 'user')},
        ),
    ]
