# Generated by Django 5.2.13 on 2026-06-25 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamecomment_gamecommentreaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='games.gamecomment'),
        ),
        migrations.AddIndex(
            model_name='gamecomment',
            index=models.Index(fields=['game', 'parent', '-created_at'], name='games_comment_thread_idx'),
        ),
    ]
