# Generated by Django 5.2.14 on 2026-05-29 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(choices=[('BUY', 'Buy'), ('CONSIDER', 'Consider'), ('WAIT', 'Wait')], default='WAIT', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='games.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_vs_low_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('days_since_last_discount', models.PositiveIntegerField(default=0)),
                ('average_discount_interval', models.PositiveIntegerField(default=0)),
                ('discount_frequency', models.PositiveIntegerField(default=0)),
                ('platform_price_rank', models.PositiveIntegerField(default=1)),
                ('pattern_label', models.CharField(default='UNKNOWN', max_length=40)),
                ('explanation', models.TextField()),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='recommendations.recommendation')),
            ],
        ),
    ]
