# Generated by Codex on 2026-06-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameAIAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "decision",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("CONSIDER", "Consider"), ("WAIT", "Wait")],
                        default="WAIT",
                        max_length=20,
                    ),
                ),
                ("recommendation_text", models.TextField()),
                ("pattern_label", models.CharField(default="UNKNOWN", max_length=40)),
                ("pattern_analysis", models.TextField()),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("price_fingerprint", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=40)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ai_analysis", to="games.game"),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(fields=["game", "generated_at"], name="recommenda_game_id_de2a3c_idx"),
                    models.Index(fields=["price_fingerprint", "prompt_version"], name="recommenda_price_f_80b28c_idx"),
                ],
            },
        ),
    ]
