# Generated by Django 5.2.15 on 2026-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_usergameaianalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaianalysis',
            name='prompt_version',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='usergameaianalysis',
            name='prompt_version',
            field=models.CharField(max_length=80),
        ),
    ]
